import Footer from "./componentes/Footer"
import Menu from "./componentes/Menu"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body>
        <Menu/>
        {children}
        
      <div>
         <h3>Kethiney</h3>
      </div>
      <div>
        <Footer/>
      </div>
      </body>
    </html>
  )
}
